name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build for Linux
      run: dotnet publish -r linux-x64 --configuration ReleaseComplete
    - name: Build for Windows
      run: dotnet publish -r win-x64 --configuration ReleaseComplete
    - name: Upload artifact - Linux
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Ghoplin
        path: Ghoplin/bin/ReleaseComplete/netcoreapp3.1/linux-x64/publish/Ghoplin
    - name: Upload artifact - Windows
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Ghoplin.exe
        path: Ghoplin/bin/ReleaseComplete/netcoreapp3.1/win-x64/publish/Ghoplin.exe
    - name: Make Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Ghoplin/bin/ReleaseComplete/netcoreapp3.1/linux-x64/publish/Ghoplin
          Ghoplin/bin/ReleaseComplete/netcoreapp3.1/win-x64/publish/Ghoplin.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
